name: upapi
channels:
  - conda-forge
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.13.2
  - debugpy=1.8.12
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.32.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libexpat=2.6.4
  - libffi=3.4.6
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.4.1
  - packaging=24.2
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=25.0.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.50
  - psutil=6.1.1
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=26.2.1
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - zeromq=4.3.5
  - zipp=3.21.0
  - pip:
    - certifi==2025.1.31
    - charset-normalizer==3.4.1
    - idna==3.10
    - numpy==2.2.3
    - pandas==2.2.3
    - python-dotenv==1.0.1
    - pytz==2025.1
    - requests==2.32.3
    - tzdata==2025.1
    - urllib3==2.3.0
